name: TCC compiler

on:
  [push, pull_request]

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: cmd /c build.bat

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
          name: Releases
          path: bin
