name: TCC compiler

on:
  [push, pull_request]

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: cmd /c build.bat

    - name: Upload x86
      uses: actions/upload-artifact@v2
      with:
          name: examples_x86
          path: bin/x86
          
    - name: Upload x64
      uses: actions/upload-artifact@v2
      with:
          name: examples_x64
          path: bin/x64
